const ACTIONS = [
  'view',
  'create',
  'update',
  'delete',
  'assign',
  'import',
  'approve',
  'reject',
  'comment',
  'upload',
  'download',
  'export',
  'manage',
  'reopen',
  'close',
];
const DATA_SCOPES = [
  'OWN',
  'ASSIGNED',
  'TEAM',
  'MULTIPLE_TEAMS',
  'DEPARTMENT',
  'BUSINESS_UNIT',
  'MULTIPLE_BUSINESS_UNITS',
  'COMPANY',
];
const LEGACY_SCOPES = [
  'all',
  'community',
  'department',
  'team',
  'assigned',
  'self',
  'linked',
  'none',
];
const SCOPES = [...LEGACY_SCOPES, ...DATA_SCOPES];
const USER_TYPES = ['employee', 'client', 'vendor', 'contractor'];
const ACCOUNT_STATUSES = ['invited', 'active', 'suspended', 'inactive'];

const PERMISSION_RESOURCES = [
  'dashboard',
  'business_os',
  'sales_crm',
  'leads',
  'clients',
  'follow_ups',
  'proposals',
  'pipelines',
  'communication',
  'marketing',
  'campaigns',
  'accounting',
  'quotations',
  'invoices',
  'payments',
  'expenses',
  'projects',
  'tasks',
  'team_workload',
  'daily_reports',
  'attendance',
  'leave',
  'documents',
  'employee_documents',
  'employees',
  'employee_profiles',
  'employee_salary',
  'users',
  'teams',
  'meetings',
  'permissions',
  'roles',
  'settings',
  'whatsapp',
  'vendors',
  'reports',
  'audit_logs',
  'reimbursements',
  'financial_profitability',
  'password_reset',
  'user_activation',
  'permission_management',
];

const MODULES = [
  { key: 'dashboard', label: 'Dashboard', resources: ['dashboard', 'reports', 'settings'] },
  { key: 'business_os', label: 'Business OS', resources: ['business_os'] },
  {
    key: 'sales',
    label: 'Sales / Clients',
    resources: ['sales_crm', 'leads', 'clients', 'follow_ups', 'proposals', 'pipelines'],
  },
  { key: 'quotations', label: 'Quotations', resources: ['quotations'] },
  { key: 'communication', label: 'Communication', resources: ['communication'] },
  { key: 'marketing', label: 'Marketing', resources: ['marketing', 'campaigns'] },
  {
    key: 'accounting',
    label: 'Accounting',
    resources: [
      'accounting',
      'invoices',
      'payments',
      'expenses',
      'reimbursements',
      'financial_profitability',
    ],
  },
  {
    key: 'projects',
    label: 'Project Work',
    resources: ['projects', 'tasks', 'team_workload', 'daily_reports', 'vendors'],
  },
  { key: 'documents', label: 'Documents', resources: ['documents'] },
  {
    key: 'employees',
    label: 'Employees',
    resources: [
      'employees',
      'employee_profiles',
      'employee_documents',
      'employee_salary',
      'attendance',
      'leave',
      'users',
      'teams',
      'password_reset',
      'user_activation',
    ],
  },
  { key: 'meetings', label: 'Meetings', resources: ['meetings'] },
  { key: 'whatsapp', label: 'WhatsApp', resources: ['whatsapp'] },
  {
    key: 'permissions',
    label: 'Permissions',
    resources: ['permissions', 'roles', 'permission_management', 'audit_logs'],
  },
];

const UNIVERSAL_COMMUNITIES = [
  { key: 'marketing', name: 'BrainADZ Marketing', universal: true, locked: true },
  { key: 'live', name: 'BrainADZ Live', universal: true, locked: true },
  { key: 'exhibition', name: 'BrainADZ Exhibits', universal: true, locked: true },
];

const DEPARTMENT_SEEDS = [
  {
    name: 'Marketing',
    slug: 'marketing',
    icon: 'Megaphone',
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: ['dashboard', 'marketing', 'communication', 'projects', 'documents'],
  },
  {
    name: 'Creative',
    slug: 'creative',
    icon: 'Palette',
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: ['dashboard', 'projects', 'documents', 'communication'],
  },
  {
    name: 'Development',
    slug: 'development',
    icon: 'Code2',
    isCompanyWide: true,
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: ['dashboard', 'projects', 'documents', 'communication'],
  },
  {
    name: '3D Team',
    slug: '3d-team',
    icon: 'Box',
    businessUnitKeys: ['exhibition'],
    defaultModuleKeys: ['dashboard', 'projects', 'documents'],
  },
  {
    name: 'Accounts',
    slug: 'accounts',
    icon: 'ReceiptText',
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: ['dashboard', 'accounting', 'quotations', 'documents'],
  },
  {
    name: 'HR',
    slug: 'hr',
    icon: 'UsersRound',
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: ['dashboard', 'employees', 'documents', 'projects'],
  },
  {
    name: 'Sales',
    slug: 'sales',
    icon: 'Handshake',
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: [
      'dashboard',
      'sales',
      'quotations',
      'communication',
      'meetings',
      'whatsapp',
      'documents',
    ],
  },
  {
    name: 'Vendors',
    slug: 'vendors',
    icon: 'Truck',
    businessUnitKeys: ['marketing', 'live', 'exhibition'],
    defaultModuleKeys: ['dashboard', 'projects', 'documents', 'communication'],
  },
  {
    name: 'Production',
    slug: 'production',
    icon: 'Factory',
    businessUnitKeys: ['exhibition'],
    defaultModuleKeys: ['dashboard', 'projects', 'documents', 'meetings'],
  },
];

const allPermission = (resource, scope = 'COMPANY') => ({ resource, actions: [...ACTIONS], scope });
const selectedPermissions = (resources, actions, scope) =>
  resources.map((resource) => ({ resource, actions, scope }));
const operationalResources = PERMISSION_RESOURCES.filter(
  (resource) =>
    !['permissions', 'roles', 'permission_management', 'audit_logs', 'employee_salary'].includes(
      resource,
    ),
);
const contributorActions = ['view', 'create', 'update', 'comment', 'upload', 'download'];
const managerActions = [
  'view',
  'create',
  'update',
  'assign',
  'import',
  'approve',
  'reject',
  'comment',
  'upload',
  'download',
  'export',
  'reopen',
  'close',
];

const functionalRole = ({
  roleKey,
  roleLabel,
  hierarchyLevel,
  description,
  defaultDataScope,
  resources,
  actions,
  roleGroup,
  allowedUserTypes = ['employee'],
}) => ({
  roleKey,
  roleLabel,
  hierarchyLevel,
  description,
  defaultDataScope,
  defaultScope: defaultDataScope,
  systemRole: true,
  roleGroup,
  allowedUserTypes,
  permissions: selectedPermissions(resources, actions, defaultDataScope),
});

const ROLE_TEMPLATES = [
  {
    roleKey: 'super_admin',
    roleLabel: 'Super Admin',
    hierarchyLevel: 100,
    description: 'Locked complete company access.',
    defaultDataScope: 'COMPANY',
    defaultScope: 'COMPANY',
    locked: true,
    systemRole: true,
    roleGroup: 'Platform',
    allowedUserTypes: USER_TYPES,
    permissions: PERMISSION_RESOURCES.map((resource) => allPermission(resource)),
  },
  {
    roleKey: 'company_admin',
    roleLabel: 'Company Admin',
    hierarchyLevel: 90,
    description: 'Full company operations except Super Admin control.',
    defaultDataScope: 'COMPANY',
    defaultScope: 'COMPANY',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: [
      ...operationalResources.map((resource) => allPermission(resource)),
      ...selectedPermissions(
        ['permissions', 'roles', 'permission_management', 'audit_logs'],
        ['view', 'create', 'update', 'assign', 'export', 'manage'],
        'COMPANY',
      ),
    ],
  },
  {
    roleKey: 'business_unit_head',
    roleLabel: 'Business Unit Head',
    hierarchyLevel: 80,
    description: 'Full access inside assigned business units.',
    defaultDataScope: 'MULTIPLE_BUSINESS_UNITS',
    defaultScope: 'MULTIPLE_BUSINESS_UNITS',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      operationalResources,
      ACTIONS.filter((action) => action !== 'manage'),
      'MULTIPLE_BUSINESS_UNITS',
    ),
  },
  {
    roleKey: 'department_head',
    roleLabel: 'Department Head',
    hierarchyLevel: 70,
    description: 'Manages an assigned department and its teams.',
    defaultDataScope: 'DEPARTMENT',
    defaultScope: 'DEPARTMENT',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      operationalResources,
      ACTIONS.filter((action) => !['delete', 'manage'].includes(action)),
      'DEPARTMENT',
    ),
  },
  {
    roleKey: 'department_manager',
    roleLabel: 'Department Manager',
    hierarchyLevel: 65,
    description: 'Runs department operations under the Department Head.',
    defaultDataScope: 'DEPARTMENT',
    defaultScope: 'DEPARTMENT',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      operationalResources,
      ['view', 'create', 'update', 'assign', 'approve', 'comment', 'upload', 'download', 'export'],
      'DEPARTMENT',
    ),
  },
  {
    roleKey: 'senior_manager',
    roleLabel: 'Senior Manager',
    hierarchyLevel: 60,
    description: 'Manages multiple assigned teams.',
    defaultDataScope: 'MULTIPLE_TEAMS',
    defaultScope: 'MULTIPLE_TEAMS',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      operationalResources,
      ['view', 'create', 'update', 'assign', 'approve', 'comment', 'upload', 'download', 'export'],
      'MULTIPLE_TEAMS',
    ),
  },
  functionalRole({
    roleKey: 'sales_manager',
    roleLabel: 'Sales Manager',
    hierarchyLevel: 55,
    description: 'Manages the sales pipeline, team follow-ups, quotations and meetings.',
    defaultDataScope: 'TEAM',
    roleGroup: 'Sales',
    resources: [
      'dashboard',
      'reports',
      'settings',
      'sales_crm',
      'leads',
      'clients',
      'follow_ups',
      'proposals',
      'pipelines',
      'quotations',
      'communication',
      'meetings',
      'documents',
      'whatsapp',
    ],
    actions: managerActions,
  }),
  functionalRole({
    roleKey: 'marketing_manager',
    roleLabel: 'Marketing Manager',
    hierarchyLevel: 55,
    description: 'Manages campaigns, communication and marketing delivery.',
    defaultDataScope: 'TEAM',
    roleGroup: 'Marketing',
    resources: [
      'dashboard',
      'reports',
      'settings',
      'marketing',
      'campaigns',
      'communication',
      'projects',
      'tasks',
      'team_workload',
      'documents',
    ],
    actions: managerActions,
  }),
  functionalRole({
    roleKey: 'accounts_manager',
    roleLabel: 'Accounts Manager',
    hierarchyLevel: 55,
    description: 'Manages quotations, invoices, payments, expenses and profitability.',
    defaultDataScope: 'DEPARTMENT',
    roleGroup: 'Accounts',
    resources: [
      'dashboard',
      'reports',
      'settings',
      'accounting',
      'quotations',
      'invoices',
      'payments',
      'expenses',
      'reimbursements',
      'financial_profitability',
      'documents',
    ],
    actions: managerActions,
  }),
  functionalRole({
    roleKey: 'project_manager',
    roleLabel: 'Project Manager',
    hierarchyLevel: 55,
    description: 'Plans projects, assigns tasks and manages team delivery.',
    defaultDataScope: 'TEAM',
    roleGroup: 'Delivery',
    resources: [
      'dashboard',
      'reports',
      'settings',
      'projects',
      'tasks',
      'team_workload',
      'daily_reports',
      'vendors',
      'documents',
      'meetings',
      'communication',
    ],
    actions: managerActions,
  }),
  functionalRole({
    roleKey: 'hr_manager',
    roleLabel: 'HR Manager',
    hierarchyLevel: 55,
    description: 'Manages employee records, attendance, leave and account lifecycle.',
    defaultDataScope: 'DEPARTMENT',
    roleGroup: 'HR',
    resources: [
      'dashboard',
      'reports',
      'settings',
      'employees',
      'employee_profiles',
      'employee_documents',
      'attendance',
      'leave',
      'users',
      'teams',
      'password_reset',
      'user_activation',
      'documents',
    ],
    actions: managerActions,
  }),
  functionalRole({
    roleKey: 'operations_exhibition_manager',
    roleLabel: 'Exhibition Operations Manager',
    hierarchyLevel: 55,
    description: 'Manages exhibition production, vendors, projects and field delivery.',
    defaultDataScope: 'TEAM',
    roleGroup: 'Operations',
    resources: [
      'dashboard',
      'reports',
      'settings',
      'projects',
      'tasks',
      'team_workload',
      'daily_reports',
      'vendors',
      'documents',
      'meetings',
      'communication',
    ],
    actions: managerActions,
  }),
  {
    roleKey: 'manager',
    roleLabel: 'Manager',
    hierarchyLevel: 50,
    description: 'Manages assigned teams and team data.',
    defaultDataScope: 'TEAM',
    defaultScope: 'TEAM',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      operationalResources,
      ['view', 'create', 'update', 'assign', 'approve', 'comment', 'upload', 'download'],
      'TEAM',
    ),
  },
  {
    roleKey: 'team_lead',
    roleLabel: 'Team Lead',
    hierarchyLevel: 40,
    description: 'Coordinates daily work for an assigned team.',
    defaultDataScope: 'TEAM',
    defaultScope: 'TEAM',
    systemRole: true,
    roleGroup: 'Leadership',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      operationalResources,
      ['view', 'create', 'update', 'assign', 'comment', 'upload', 'download'],
      'TEAM',
    ),
  },
  functionalRole({
    roleKey: 'sales_executive',
    roleLabel: 'Sales Executive',
    hierarchyLevel: 25,
    description: 'Works assigned leads, clients, follow-ups, quotations and sales meetings.',
    defaultDataScope: 'ASSIGNED',
    roleGroup: 'Sales',
    resources: [
      'dashboard',
      'settings',
      'sales_crm',
      'leads',
      'clients',
      'follow_ups',
      'proposals',
      'pipelines',
      'quotations',
      'communication',
      'meetings',
      'documents',
      'whatsapp',
    ],
    actions: contributorActions,
  }),
  functionalRole({
    roleKey: 'marketing_executive',
    roleLabel: 'Marketing Executive',
    hierarchyLevel: 25,
    description: 'Works assigned campaigns, content tasks and communications.',
    defaultDataScope: 'ASSIGNED',
    roleGroup: 'Marketing',
    resources: [
      'dashboard',
      'settings',
      'marketing',
      'campaigns',
      'communication',
      'projects',
      'tasks',
      'daily_reports',
      'documents',
    ],
    actions: contributorActions,
  }),
  functionalRole({
    roleKey: 'accountant',
    roleLabel: 'Accountant',
    hierarchyLevel: 25,
    description: 'Works assigned accounting, invoice, payment and expense records.',
    defaultDataScope: 'ASSIGNED',
    roleGroup: 'Accounts',
    resources: [
      'dashboard',
      'settings',
      'accounting',
      'quotations',
      'invoices',
      'payments',
      'expenses',
      'reimbursements',
      'documents',
    ],
    actions: contributorActions,
  }),
  functionalRole({
    roleKey: 'operations_executive',
    roleLabel: 'Operations Executive',
    hierarchyLevel: 25,
    description: 'Works assigned production tasks, vendors, documents and meetings.',
    defaultDataScope: 'ASSIGNED',
    roleGroup: 'Operations',
    resources: [
      'dashboard',
      'settings',
      'projects',
      'tasks',
      'daily_reports',
      'vendors',
      'documents',
      'meetings',
      'communication',
    ],
    actions: contributorActions,
  }),
  {
    roleKey: 'employee',
    roleLabel: 'Employee',
    hierarchyLevel: 10,
    description: 'Own and assigned work only.',
    defaultDataScope: 'ASSIGNED',
    defaultScope: 'ASSIGNED',
    systemRole: true,
    roleGroup: 'General',
    allowedUserTypes: ['employee'],
    permissions: selectedPermissions(
      ['dashboard', 'projects', 'tasks', 'daily_reports', 'documents', 'meetings', 'settings'],
      ['view', 'create', 'update', 'comment', 'upload', 'download'],
      'ASSIGNED',
    ),
  },
  functionalRole({
    roleKey: 'client_viewer',
    roleLabel: 'Client Viewer',
    hierarchyLevel: 5,
    description: 'Read-only access to linked client projects, documents and meetings.',
    defaultDataScope: 'OWN',
    roleGroup: 'External',
    allowedUserTypes: ['client'],
    resources: ['dashboard', 'projects', 'tasks', 'documents', 'meetings'],
    actions: ['view', 'download'],
  }),
  functionalRole({
    roleKey: 'vendor_contractor',
    roleLabel: 'Vendor / Contractor',
    hierarchyLevel: 5,
    description: 'Limited access to assigned vendor work, tasks and shared documents.',
    defaultDataScope: 'ASSIGNED',
    roleGroup: 'External',
    allowedUserTypes: ['vendor', 'contractor'],
    resources: ['dashboard', 'projects', 'tasks', 'vendors', 'documents', 'meetings'],
    actions: ['view', 'update', 'comment', 'upload', 'download'],
  }),
  {
    roleKey: 'custom_role',
    roleLabel: 'Custom Role',
    hierarchyLevel: 20,
    description: 'Configurable role created by Super Admin.',
    defaultDataScope: 'ASSIGNED',
    defaultScope: 'ASSIGNED',
    systemRole: true,
    roleGroup: 'Custom',
    allowedUserTypes: USER_TYPES,
    permissions: [],
  },
];

const ROLE_DEPARTMENT_SLUGS = {
  sales_manager: ['sales'],
  sales_executive: ['sales'],
  marketing_manager: ['marketing'],
  marketing_executive: ['marketing'],
  accounts_manager: ['accounts'],
  accountant: ['accounts'],
  hr_manager: ['hr'],
  project_manager: ['creative', 'development', '3d-team', 'production'],
  operations_exhibition_manager: ['3d-team', 'production', 'vendors'],
  operations_executive: ['3d-team', 'production', 'vendors'],
  vendor_contractor: ['vendors'],
};

const DEFAULT_ROLES = ROLE_TEMPLATES;
const CRM_ROLE_KEYS = ROLE_TEMPLATES.map((role) => role.roleKey);
const COMMUNITY_KEYS = UNIVERSAL_COMMUNITIES.map((community) => community.key);

module.exports = {
  ACTIONS,
  DATA_SCOPES,
  SCOPES,
  USER_TYPES,
  ACCOUNT_STATUSES,
  PERMISSION_RESOURCES,
  MODULES,
  UNIVERSAL_COMMUNITIES,
  DEPARTMENT_SEEDS,
  ROLE_TEMPLATES,
  ROLE_DEPARTMENT_SLUGS,
  DEFAULT_ROLES,
  CRM_ROLE_KEYS,
  COMMUNITY_KEYS,
};
